# Database
# Do not use this in production
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%prod.quarkus.hibernate-orm.schema-management.strategy=update

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/actualiteiten
# Override for production - values will come from the secret
%prod.quarkus.datasource.jdbc.url=
%prod.quarkus.datasource.username=
%prod.quarkus.datasource.password=

# Profiel Service client (for koppelcode resolution)
quarkus.rest-client.profiel-service.url=http://localhost:8080
%prod.quarkus.rest-client.profiel-service.url=

quarkus.datasource.metrics.enabled=true
